PychamProject/BulletinProject/board/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bulletin/', include('bulletin_board.urls')),
]

PychamProject/BulletinProject/bulletin_board/urls.py
from django.urls import path
from . import views

app_name = 'bulletin_board'
urlpatterns = [ #주소 맵핑
    path('', views.index, name='index'),
    path('create/', views.create_bulletin, name='new_bulletin'),
    path('add/', views.add_bulletin, name='insert_bulletin'),
    path('<int:bulletin_id>/', views.view_bulletin, name='view'),
    path('update/<int:bulletin_id>/', views.update_bulletin, name='update'),
    path('delete/<int:bulletin_id>/', views.delete_bulletin, name='delete'),

]

PychamProject/BulletinProject/bulletin_board/models.py
from django.db import models
from django.utils.timezone import now

# Create your models here.
class Bulletin(models.Model):
    title = models.CharField(max_length=100)
    content = models.CharField(max_length=2000)
    writeDate = models.DateTimeField(default=now, editable=False) #editable=False 수정불가
    name = models.CharField(max_length=50)
    password = models.CharField(max_length=50)

    def __str__(self):
        return self.title

PychamProject/BulletinProject/bulletin_board/views.py
from django.shortcuts import render, get_object_or_404
from .models import Bulletin
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.utils import timezone


# Create your views here.
# 1. 함수 2. 클래스(재사용성 大)

def index(request):
    # 게시글 전체 목록조회
    bulletin_list = Bulletin.objects.all().order_by('-writeDate') # 작성일 desc로 정렬
    context = {'bulletin_list': bulletin_list}
    return render(request, 'bulletin/index.html', context)

def create_bulletin(request):
    # 새 글 작성 get
    return render(request, 'bulletin/create_bulletin.html')

def add_bulletin(request):
    # 새 글 작성 post
    bulletin = Bulletin()
    bulletin.title = request.POST['title']
    bulletin.content =  request.POST['content']
    bulletin.name =  request.POST['name']
    bulletin.password =  request.POST['pincode']
    bulletin.save()

    # redirect
    return HttpResponseRedirect(reverse('bulletin_board:index'))


def view_bulletin(request, bulletin_id):
    # 글 조회
    bulletin = get_object_or_404(Bulletin, pk=bulletin_id)
    # get_object_or_404 pk값이 없을땐 404 error 페이지 출력
    return render(request, 'bulletin/detail.html', {'bulletin': bulletin})


def update_bulletin(request, bulletin_id):
    # 글 수정
    bulletin = Bulletin.objects.get(id=bulletin_id)

    if request.method == "POST":
        bulletin.title = request.POST['title']
        bulletin.content = request.POST['content']
        bulletin.writeDate = timezone.datetime.now()
        bulletin.save()
        return HttpResponseRedirect(reverse('bulletin_board:view', args=(bulletin_id,)))

    else:
        return render(request, 'bulletin/detail.html', {'bulletin': bulletin})


def delete_bulletin(request, bulletin_id):
    bulletin = Bulletin.objects.get(id=bulletin_id)
    bulletin.delete()
    return HttpResponseRedirect(reverse('bulletin_board:index'))

PychamProject/BulletinProject/templates/bulletin/create_bulletin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>새 글</title>
    <script>
      function backToList(obj){
        obj.action="{% url 'bulletin_board:index' %}"; // bulletin_board의 urls.py에서 맵핑
        obj.submit();
      }
    </script>
    <style>
	.class-caption {
		width:100px;
	}
	.class-content {
		width:500px;
	}
    </style>
</head>
<body>
    <!--
    csrf 공격
    client가 요청하면 django가 form을 넘겨주는 상황
    중간에 가로채서 다른 내용을 넣을 수 있음
    브라우저에서 시크릿 키를 받아서 맞는지 체크하고 업로드
    {% csrf_token %}
    브라우저에 시크릿 키 전달
    -->
    <h1 style="text-align: center">새글 쓰기</h1>
	<form name="bulletin_form" method="post" action="{% url 'bulletin_board:insert_bulletin' %}">
        {% csrf_token %}
	<table border=0 align="center">
	<tbody>
		<tr>
			<td align="right" class="class-caption">글제목:</td>
			<td><input type="text" maxlength="500" name="title" class="class-content"/></td>
		</tr>
		<tr>
			<td align="right" valign="top" class="class-caption"><br>글내용:</td>
			<td><textarea name="content" rows="10" cols="65" maxlength="2000" class="class-content">
			</textarea></td>
		</tr>
		<tr>
			<td align="right" class="class-caption">작성자:</td>
			<td><input type="text" maxlength="50" name="name" class="class-content"/></td>
		</tr>
        <tr>
	<td align="right" class="class-caption">비밀번호:</td>
	<td><input type="password" maxlength="50" name="pincode" class="class-content"/></td>
	</tr>
	<tr>
		<td align="right"></td>
		<td><input type="submit" value="글쓰기" />
		<input type=button value="목록보기" onClick="backToList(bulletin_form)" /></td>
	</tr>
	</tbody>
	</table>
    </form>
</body>
</html>

PychamProject/BulletinProject/templates/bulletin/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>상세 보기</title>
    <style>
        #tr_edit {
            display: none;
        }
        .hidden-passwd {
            display: none;
        }
       .class-caption {
	width:150px;
       }
       .class-content {
	width:500px;
       }
    </style>
    <script>
        function backToList(frm) {
            frm.action = "{% url 'bulletin_board:index' %}";
            frm.submit();
        }

        function fn_enable() {
            document.querySelector("#i_title").disabled = false;
            document.querySelector("#i_content").disabled = false;
            document.querySelector("#tr_edit").style.display = "table-row";
            document.querySelector("#tr_button").style.display = "none";
        }

        function fn_modify_bulletin(frm, original_password, confirm_password) {
        	if(original_password != confirm_password) {
        		alert('비밀번호를 확인하세요')
        		return false;
        	}
        	frm.action = "{% url 'bulletin_board:update' bulletin.id %}"
        	frm.submit()
        }

        function fn_remove_bulletin(frm, original_password, confirm_password) {
        	if(original_password != confirm_password) {
        		alert('비밀번호를 확인하세요')
        		return false;
        	}
        	frm.action = "{% url 'bulletin_board:delete' bulletin.id %}"
        	frm.submit()
        }
    </script>
</head>
<body>
    <form name="bulletin_form" method="post">
        {% csrf_token %}
	<table border="0" align="center">
	<tbody>
		<tr>
			<td class="class-caption" align="center" bgcolor="#ffcc00">글번호</td>
			<td><input type="text" class="class-content" value="{{bulletin.id }}" disabled />
			</td> <!-- 템플릿 엔진에서 변수 사용법 {{bulletin.id }}-->
		</tr>
		<tr>
			<td class="class-caption" align="center" bgcolor="#ffcc00">작성자 아이디</td>
			<td><input type="text" class="class-content" value="{{bulletin.name }}" name="writer" disabled /></td>
		</tr>
        <tr>
            <td class="hidden-passwd"><<input  id="passwd_value" type="text" value="{{bulletin.password }}"/>/td>
        </tr>
	<tr>
		<td class="class-caption" align="center" bgcolor="#ffcc00">제목</td>
		<td><input type="text" class="class-content" value="{{bulletin.title }}" name="title" id="i_title" disabled /></td>
	</tr>
	<tr>
		<td class="class-caption" align="center" bgcolor="#ffcc00">내용</td>
		<td><textarea rows="20" cols="60" class="class-content" name="content" id="i_content"
			disabled>{{bulletin.content }}</textarea></td>
	</tr>
	<tr>
		<td class="class-caption" align=center bgcolor="#ffcc00">등록일자</td>
		<td><input type="text" class="class-content" value="{{bulletin.writeDate }}" disabled />
		</td>
	</tr>
	<tr>
		<td class="class-caption" align=center bgcolor="#ffcc00">비밀번호</td>
		<td><input type="password" class="class-content" id="in_passwd"/>
		</td>
	</tr>
	<tr id="tr_edit">
		<td colspan=2 align="center">
                <input type="button" value="수정반영하기"
	   onClick="fn_modify_bulletin(bulletin_form, passwd_value.value, in_passwd.value)">
                <input type="button" value="취소" onclick="backToList(bulletin_form)">
	</td>
	</tr>

            <tr id="tr_button">
                <td colspan=2 align=center>
                    <input type=button value="수정하기"	onClick="fn_enable(bulletin_form)">
                    <input type=button value="삭제하기" onclick="fn_remove_bulletin(bulletin_form, passwd_value.value, in_passwd.value)">
                    <input type=button value="리스트로 돌아가기" onclick="backToList(bulletin_form)">
                </td>
            </tr>
	    </tbody>
	    </table>
    </form>
</body>
</html>

PychamProject/BulletinProject/templates/bulletin/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>글목록</title>
    <style>
        .rm_underline {
            text-decoration: none;
        }
        .new_bulletin {
            text-align: center;
            font-size: 30px;
            display: block;
        }
    </style>
</head>
<body>
    <table align="center" border="1" style="width:80%">
        <thead>
            <tr align="center" bgcolor="yellow">
                <th>글번호</th>
                <th>작성자</th>
                <th>제목</th>
                <th>작성일</th>
            </tr>
        </thead>
    {% if bulletin_list %} <!-- template language -->
    <tbody>
        {% for bulletin in bulletin_list %}
            <tr align="center">
                <td style="width:30px">{{bulletin.id}}</td>
                <td style="width:50px">{{bulletin.name}}</td>
                <td align='left' style="width:200px">
                    <span style="padding-right: 30px"></span>
                    <a class='rm_underline' href="{% url 'bulletin_board:view' bulletin.id %}">{{bulletin.title}}</a>
                </td>
                <td style="width:100px">{{bulletin.writeDate}}</td>
            </tr>
        {% endfor %}
    </tbody>
    {% else %}
    <tbody>
        <tr>
            <td colspan="4">
                <p align="center">
                    <b><span style="font-size: 15pt;">등록된 글이 없습니다.</span></b>
                </p>
            </td>
        </tr>
    </tbody>
    {% endif %}
    </table>
    <a class="rm_underline" href="{% url 'bulletin_board:new_bulletin' %}">
	<span class="new_bulletin">글쓰기</span>
    </a>
</body>
</html>